### ISSUE TITLE
Not enough bandwitdth for feedback control

### ISSUE THREAD

**Issue by FrancescoRuscelli** [ADVRHumanoids/XBotControl#10]
Even the fast filter (5 Hz) causes instabilities with feedback control (ComStabilizer). I suggest to create an empty profile filter

**Comment by alaurenzi** [comment]
I'll add that setting an extremely high cutoff (200 Hz) solves any problem.

**Comment by liesrock** [comment]
I would prefer to have another profile with extremely high cutoff frequency: what do you think @alaurenzi ?

**Comment by alaurenzi** [comment]
Yes, we can introduce a `filter_profile_none` with 200Hz cutoff

**Comment by liesrock** [comment]
This was solved by @alaurenzi
