### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nkashiri** [ADVRHumanoids/XBotControl#11]
Hi @liesrock 
I think it would be nice to have a list of requirements for the installation of the DEB file. 
I remember there used be to a basic script in the initial superbuild installation that would take care of prerequisites. Does the DEB file include such a thing? (I guess no, since I get a list of dependency errors) 
Would you make a list of dependencies (or if possible, a similar basic script as we used to have)?

Thanks
Navvab

**Comment by nkashiri** [comment]
I found the answer in https://github.com/ADVRHumanoids/XBotControl

**Comment by nkashiri** [comment]
On the configuration section, I think it is better to explicitly mention adding the following line to .bashrc
. /opt/xbot/build/install/share/xbot/setup.bash
and then sourcing it by source ~/.bashrc

**Comment by liesrock** [comment]
Thanks for the suggestions, should be now fixed in a better structure now

**Comment by nkashiri** [comment]
At the "Quick Start" page, I believe we are missing the way of compiling and installing for the generated plugin

**Comment by nkashiri** [comment]
at the "Basic Example" page, for running rviz, the following part:
_Remind to select an existent "Fixed Frame" from the list._
should be completed to:
_Remind to select "world" for "Fixed Frame" in "Global Options"._

**Comment by nkashiri** [comment]
In the configure section of Installation page, I believe there is a repetition.

**Comment by liesrock** [comment]
Thanks a lot @nkashiri, I close this: we can open new issues when you find problems in the documentation
