### ISSUE TITLE
xbot gazebo controller 

### ISSUE THREAD

**Issue by nkashiri** [ADVRHumanoids/XBotControl#13]
Hi @liesrock 
The Gazebo doesn't get the Xbot Controller (with roslaunch centauro_gazebo centauro_world.launch paused:=false), the robot is not controlled. 
Do I need to change something?

**Comment by liesrock** [comment]
I tested this using the centauro basuc config: which config are you using?

**Comment by nkashiri** [comment]
I think I set the same file:
$ get_xbot_config 
/opt/xbot/build/install/share/xbot/configs/CentauroConfig/centauro_basic.yaml

**Comment by nkashiri** [comment]
@liesrock: Looks related with the Gazebo version: 7 does not seems supported by the v1.1.1 of the binaries

**Comment by liesrock** [comment]
It should be pointed out that the supported version is currently Gazebo 8: if you fix the issue upgrading it I will write this down explicitly in the documentation

**Comment by nkashiri** [comment]
Yes, it works with the upgrade of Gazebo to version 8, and re-installation of ros and XBot. 
To avoid the removal and re-installation, I suggest adding the procedure to the installation section, here is what I did:
1 - Setup your computer to accept software from packages.osrfoundation.org.
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'

You can check to see if the file was written correctly. For example, in Ubuntu Xenial, you can type:
$ cat /etc/apt/sources.list.d/gazebo-stable.list
deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main
2- Setup keys
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -

3- First update the debian database:
sudo apt-get update

4- follow instructions at https://medium.com/@abhiksingla10/setting-up-ros-kinetic-and-gazebo-8-or-9-70f2231af21a
