### ISSUE TITLE
Problems when sending torque references

### ISSUE THREAD

**Issue by Yisoo-Lee** [ADVRHumanoids/XBotControl#17]
Hi @liesrock ,
It seems like sending torque reference through function "_robot->setEffortReference_" or "_model->setJointEffort_" doesn't work. (Both stiffness and damping are set to zero before using the functions.) 
I tested some cases with @EnricoMingo  to control joint angles with torque references, but all the results show weird behavior in the simulation.
When we check the log, unlike the reference torque in the plugin I created, the 'effort_reference' in XBotCore_log has different values.  As you can see in the following plots, 'effort_reference' in XBotCore_log has a constant value.

![TorqueRef_in_PlugIn](https://user-images.githubusercontent.com/49517140/58115321-212abc00-7bfa-11e9-8166-2727b92e82da.jpg)
![effort_reference_in_XBotCore](https://user-images.githubusercontent.com/49517140/58115342-27209d00-7bfa-11e9-80cd-6883f6c4c291.jpg)

**Comment by liesrock** [comment]
Hi Yisoo, thanks a lot for the detailed description: can you give me more information on how to reproduce the issue? 

I will try to run your plugin and check what you are saying.

**Comment by Yisoo-Lee** [comment]
@liesrock , I sent the related material by email. Thank you!

**Comment by Yisoo-Lee** [comment]
There was a mistake in my code. The problem is solved now.
