### ISSUE TITLE
Gazebo somehow blocks message in XBotPlugins

### ISSUE THREAD

**Issue by XinyuanZhao** [ADVRHumanoids/XBotControl#18]
System Info: Ubuntu: 16.04; Ros: Kinetic; XBot: 1.1.2; Gazebo: 8.6

I use `std::cout` in XBotPlugins to monitor some system states in simulations. When I `roslaunch` XBotCore and Gazebo together, there is no expected message on the screen. Whereas, if I run XBotCore seperately and call the service, the outputs can be shown correctly. The following screenshots show these two situations respectively.

![Screenshot from 2019-06-27 08-41-39](https://user-images.githubusercontent.com/25267776/60242983-8340a600-98b7-11e9-90f2-2b8381a8f866.png)
![Screenshot from 2019-06-27 08-40-09](https://user-images.githubusercontent.com/25267776/60242982-82a80f80-98b7-11e9-9b74-a6e424fefbfb.png)

Q: Is it because the latest XBot depends on Gezebo8 rather than Gazebo7? I remember that I didn't meet this problem last month ... @liesrock @Ato

**Comment by liesrock** [comment]
Fixed in the lates v1.1.6: we give compatibility only with Gazebo 8
