### ISSUE TITLE
wrong msg rate in simulation

### ISSUE THREAD

**Issue by FrancescoRuscelli** [ADVRHumanoids/XBotControl#19]
When running XBotCore in simulation with gazeboros (and rosparam set /use_sim_time true):

francesco@ADVR1611L9-Linux:~$ rostopic hz /xbotcore/ros_joint_states 
subscribed to [/xbotcore/ros_joint_states]
WARNING: may be using simulated time
average rate: 636.364
	min: 0.000s max: 0.006s std dev: 0.00130s window: 127

the rate appears to be wrong, since it should be 200Hz.

**Comment by liesrock** [comment]
Can you check this with the new version v1.1.6: should be ok now.

**Comment by liesrock** [comment]
From my experience this should not occur in xbot2, if I am wrong please re-open it.
