### ISSUE TITLE
Error in last version of debians when using CartesI/O

### ISSUE THREAD

**Issue by fcaponetto** [ADVRHumanoids/XBotControl#20]
While trying running a launch file with ```/opt/ros/kinetic/lib/cartesian_interface/marker_spawner``` and ```/opt/ros/kinetic/lib/cartesian_interface/ros_server_node``` I got an error saying that it can not shared library ```librobot_state_publisher_advr_solver.so```. Indeed I checked in ```/opt/xbot/lib``` and I found that the compiled library name is ```librobot_state_publisher_solver.so```. I created a symbolic link with the correct name and now I get the following:
```
/opt/ros/kinetic/lib/cartesian_interface/marker_spawner: symbol lookup error: /opt/xbot/build/install/lib/libCartesianInterface.so: undefined symbol: _ZTVN21robot_state_publisher19RobotStatePublisherE
/opt/ros/kinetic/lib/cartesian_interface/ros_server_node: symbol lookup error: /opt/xbot/build/install/lib/libCartesianInterface.so: undefined symbol: _ZTVN21robot_state_publisher19RobotStatePublisherE
```

I am using the last version of the debians.

**Comment by liesrock** [comment]
Thanks @fcaponetto: we solved the issue installing the missing ros-kinetic-robot-state-publisher in the system.
