### ISSUE TITLE
Remove "deprecated functions" in OpenSoT

### ISSUE THREAD

**Issue by XinyuanZhao** [ADVRHumanoids/XBotControl#22]
It is a kind remind that please remove "deprecated functions" in OpenSoT integrated with XBotControl 1.1.2 at your convenience. New functions work well. @EnricoMingo

**Comment by EnricoMingo** [comment]
Hi @XinyuanZhao , yes, we are going to remove soon the deprecated methods, I will keep this open as reminder.

**Comment by XinyuanZhao** [comment]
Ok. Thank you for providing a powerful and useful tool!
