### ISSUE TITLE
Required Orocos_kdl Version Outdated 

### ISSUE THREAD

**Issue by christopherpeers** [ADVRHumanoids/XBotControl#31]
The orocos_kdl version that is required for the tutorial to build is 1.3.0 whereas the default version on ros kinetic has been updated to 1.3.2.

Issue can be avoided by making the 1.3.0 release of orocos_kdl and adding it to ros kinetic libraries.

**Comment by liesrock** [comment]
Hi @christopherpeers,

thanks for the issue: we already have this tracked here https://github.com/ADVRHumanoids/XBotControl/issues/29

So I will close this issue and keep you updated on the other (fyi @alaurenzi @EnricoMingo @DavideAntonucci )
