### ISSUE TITLE
Huge tracking error of using non-realtime ros node

### ISSUE THREAD

**Issue by XinyuanZhao** [ADVRHumanoids/XBotControl#36]
I just found that the tracking error of joint motions from a non-real-time ROS node is huge compared with that from a similar real-time XBot Plugin.

Let's take the simplest **homing** function as an example. The joint command `q_cmd` is computed by
`q_cmd = q0 + 0.5 * (1 - cos(M_PI*time_elapse/homing_time)) * (q_home - q0)`
and the control rate of both the non-real-time and real-time realizations is 200 hz.

- plot of tracking errors of a single joint (the results of other joints are similar)
![1](https://user-images.githubusercontent.com/25267776/108513831-64c8c300-72c3-11eb-8dcc-0697a3989ff4.jpg)
![2](https://user-images.githubusercontent.com/25267776/108513842-67c3b380-72c3-11eb-84ca-1691f87a5e9c.jpg)

- when I call the service `/xbotcore/set_filter_profile_fast`, the tracking error from a  non-real-time ROS node become smaller, but it's still large compared with that from a real-time plugin
![3](https://user-images.githubusercontent.com/25267776/108514329-08b26e80-72c4-11eb-82f5-31960cdf6e66.jpg)

Any ideas of the reasons and solutions? @EnricoMingo @alaurenzi

**Comment by alaurenzi** [comment]
Does this data come from the real robot?

**Comment by XinyuanZhao** [comment]
> Does this data come from the real robot?

No. The results are from simulations.

Another related concern is that the results in simulations and in experiments are different, which means we could face difficulties after transforming the code. If the results are consistent, at least we can predict the performances by simulations.

So in my opinion, either figuring out the reasons or making sure the consistency is beneficial.

**Comment by XinyuanZhao** [comment]
Hello All,

Since the tracking errors seem to be caused by time delays when running an NRT ROS node, I further checked the **approximated delays** by setting `set_filter_profile_fast` or `set_filter_profile_medium` when running an NRT homing function at 200 Hz. Here are the results:
- with  `set_filter_profile_fast`: about 75 ms
- with `set_filter_profile_medium`: about 150 ms

For your information.

**Comment by XinyuanZhao** [comment]
Hello All,

Update this issue.

We did three tests of **homing in the air** on the robot. The test configurations are shown below.
- test_1: using RT Plugin in the package `xbot2_examples`
- test_2: using non-RT ROS node, `safe filter profile`
- test_3: using non-RT ROS node, `fast filter profile`

By the way, I copied the implementation of the homing function in `xbot2_examples` to the non-RT homing function.

Here display the results of joint tracking errors.
- test_1: using RT Plugin
![RT_Plugin](https://user-images.githubusercontent.com/25267776/126061448-28481c12-da8b-43ed-8f3b-589b26ca5ad2.jpg)

- test_2: using non-RT ROS node, safe filter profile
![NRT_Safe](https://user-images.githubusercontent.com/25267776/126061459-b72083ca-bb0e-4e16-86ef-def61cfb9a31.jpg)

- test_3: using non-RT ROS node, fast filter profile
![NRT_Fast](https://user-images.githubusercontent.com/25267776/126061465-ab3bdea1-14f9-408c-8661-fb5b5ba663d6.jpg)

Obviously, all of the tracking errors are within reasonable ranges this time. But with regard to this issue, now I have two further questions.

First, why is the tracking error in test-3 is in general smaller than that in test-1? In the previous tests as shown at the beginning, the RT Plugin always had smaller tracking errors than NRT cases no matter if `fast filter profile` was used. It seems that now the RT Plugin has been safely filtered by default, right?

Second, this test is quite conservative because the robot moved without any contacts and the motion was slow (homing in 5 s). I remember that in February I tested with Arturo and we found the tracking error during locomotion could reach about **0.3 rad** (amazingly...). So I plan to test another round in the next week when we place the robot on the ground and let it walk.

Let's check later if this issue is really solved.
@alaurenzi @liesrock @DavideAntonucci @ntsagarakis

**Comment by alaurenzi** [comment]
In xbot2 reference filtering is centralized and applied to all modules.

**Comment by XinyuanZhao** [comment]
> In xbot2 reference filtering is centralized and applied to all modules.

This perfectly explains the first question. Thanks!

Talking about the filter, I remembered in February you @alaurenzi said that the error appeared between the filter and the motor (I mean, there was little error before the filter), so it's actually **not a tracking error** but a **filtering error**. Did you solve this issue when updating to Xbot 2?

**Comment by liesrock** [comment]
The issue should not be there: if you can still try it in simulation please confirm it @XinyuanZhao. For the moment I'll close.
