### ISSUE TITLE
[CartesIO 2] Cartesian Interface config.so do not find

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/XBotControl#38]
## Problem
Hi, I am opening this issue because I am occurring the following error
```
[error] in generate_jidmap: urdf does not exists! 
[error] File libModelInterface/config.so NOT found
terminate called after throwing an instance of 'std::runtime_error'
  what():  libModelInterface/config.so path must be listed inside LD_LIBRARY_PATH
[CartesioTests-2] process has died [pid 32274, exit code -6, cmd /home/liana/catkin_ws/devel/lib/cartesio_tests/CartesioTests __name:=CartesioTests __log:=/home/liana/.ros/log/f97ce514-b245-11eb-86cf-d8cb8a3f0cce/CartesioTests-2.log].
log file: /home/liana/.ros/log/f97ce514-b245-11eb-86cf-d8cb8a3f0cce/CartesioTests-2*.log
```

while I use the cartesian interface, with CartesIO 2. How can I solve it?

## How I get the problem
In detail, I followed the instruction [here](https://advrhumanoids.github.io/CartesianInterface/progr_cpp.html) to write a C++ code to command a robot with the cartesian interface. Then I build on it a ROS Node which basically wraps that code.  Here the sources:

- [CartesioTests.zip](https://github.com/ADVRHumanoids/XBotControl/files/6458684/CartesioTests.zip)

I am executing that code using this command

```
roslaunch cartesio_tests CartesioTests.launch
```

with Ubuntu 18.04 and ROS Melodic. 
For CartesIO 2, I download the binaries from [here](https://advrhumanoids.github.io/CartesianInterface/index.html). In particular, I downloaded them: [bionic-2020_06_08_19_58_19.tar.gz](https://github.com/ADVRHumanoids/XBotControl/releases/download/v2.0-devel/bionic-2020_06_08_19_58_19.tar.gz).

**Comment by lia2790** [comment]
yes @liesrock!

https://github.com/lia2790/CartesioTests

**Comment by alaurenzi** [comment]
The errors comes from the fact that the `model_type` parameter is taking its default value of `/config` [(see here)](https://github.com/lia2790/CartesioTests/blob/c2a1ad047939dc34a588bcc0b119d8c4a2d5034a/src/CartesioTestsManager.cpp#L51). You can use `RBDL` instead.

**Comment by lia2790** [comment]
Hi @alaurenzi, many thanks for your answer. Yes, the problem was that. Therefore, we can close this issue.
