### ISSUE TITLE
Using Xbot-core2 with realsensecamera:=true in Gazebo

### ISSUE THREAD

**Issue by JuanHernandez1993** [ADVRHumanoids/XBotControl#52]
Hello, 
When trying to launch xbot-core2 if the realsense camera is used in Gazebo, the following error appears:

[info][nrt_main] 'nrt_main': loaded HalManager with devices: [] 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  duplicate name '{camera_name}accel' detected
Abortado (`core' generado)

In case it helps, if Gazebo is launched without the camera, xbot-core2 works right. 
How can this be solved?
Thank you in advanced for the help.

**Comment by liesrock** [comment]
This should be linked with a not correct configuration on the model side for the Gazebo process: if you still have the issue please open it in the relevant model repo.
