### ISSUE TITLE
XBot::LibNotFound what(): libfcl.so.0.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lia2790** [ADVRHumanoids/XBotControl#53]
Hi @liesrock, @alaurenzi,

I have updated my ubuntu from 18.0 to 20.04 from scratch. Then, I have re-install all. Now, I have my Variable Impedance Modulation package which is a xbot plugin. 

After having re-install all I obtain the following error when I try to run  ` xbot2-core --simtime` 

```bash
liana@liana-Inspiron-5593:~/catkin_ws/src/VariableImpedanceModulation/configs/xbot (TaskModelAwareIM_devel)$ ./setup_xbot2_gz_centauro_right_arm.sh 
/home/liana/catkin_ws/src/VariableImpedanceModulation/configs/xbot/robot/centauro_test_4_right_arm.yaml
[warn][jm] running with disabled safety policies 
[err ][nrt_control] exception 'XBot::LibNotFound' thrown while loading plugin 'joint_impedance_controlH' 
  what(): libfcl.so.0.6: cannot open shared object file: No such file or directory 
[err ][nrt_main] exception 'XBot::LibNotFound' thrown while loading plugin 'ec_ros' 
  what(): libxbotctrl_ec_ros.so: cannot open shared object file: No such file or directory 
[ok  ][xbot2-core] started running 
[info][rt_main] xbot2 thread 'rt_main' transits to state 'Run' 
[info][nrt_control] xbot2 thread 'nrt_control' transits to state 'Run' 
[info][nrt_main] xbot2 thread 'nrt_main' transits to state 'Run' 
^C[ok  ][xbot2-core] gracefully stopping 
```

The code which generates this error is the last commit here

- [3658daa515208d9f7dca29c30ba12593068d507c](https://github.com/ADVRHumanoids/VariableImpedanceModulation/tree/3658daa515208d9f7dca29c30ba12593068d507c)

and to install both, xbot2 and cartesian interface I followed the instructions here:

- https://advrhumanoids.github.io/xbot2/quickstart.html

I have realized the problem is with that shared library and then the related LD_LIBRARY_PATH, but I do not know how to properly fix it.

Could you help me?

many thanks!

**Comment by alaurenzi** [comment]
Check that you have ros-noetic-moveit-core installed. After installing it, you must refresh your terminal since it will install a few catkin environment hooks that are supposed to update LD_LIBRARY_PATH's value.

**Comment by lia2790** [comment]
Hi @alaurenzi,

yes, with that I fixed the issue! many thanks!
It is still there the error related to  libxbotctrl_ec_ros.so, but the code seems to work anyway.
