### ISSUE TITLE
Library problem on fresh installation

### ISSUE THREAD

**Issue by edoardolamon** [ADVRHumanoids/XBotControl#6]
After the installation of the binaries I set the config file of a robot and then ran XBotCore -D. I got the following error:

XBotCore: error while loading shared libraries: liborocos-kdl.so.1.3: cannot open shared object file: No such file or directory

**Comment by liesrock** [comment]
Ciao @edoardolamon,

sorry for the late answer: I think this is related with your system packages, can you try the latest version of the framework?

Available here: https://github.com/ADVRHumanoids/XBotControl/releases/tag/v1.1.1

Documentation here: https://github.com/ADVRHumanoids/XBotControl/releases/tag/v1.1.1

**Comment by liesrock** [comment]
@edoardolamon  any chances to test this:

> Ciao @edoardolamon,
> 
> sorry for the late answer: I think this is related with your system packages, can you try the latest version of the framework?
> 
> Available here: https://github.com/ADVRHumanoids/XBotControl/releases/tag/v1.1.1
> 
> Documentation here: https://github.com/ADVRHumanoids/XBotControl/releases/tag/v1.1.1

@nkashiri is also testing this. Otherwise I will close this and I kindly ask to open new issues if you find problems.

**Comment by liesrock** [comment]
I assume it solved
